/* ============================================================
   MISSION OS — Mock Mission Data
   Complete data for 6 active space missions
   ============================================================ */

export const missions = [
  {
    id: 'MSN-001',
    name: 'ARTEMIS-VII',
    codename: 'Lunar Horizon',
    phase: 'Preliminary Design',
    phaseIndex: 3,
    healthScore: 78,
    completion: 42,
    riskLevel: 'medium',
    status: 'active',
    launchDate: '2027-03-15T14:30:00Z',
    color: '#00FF9D',
    description: 'Crewed lunar surface exploration mission targeting the South Pole-Aitken basin for extended duration habitation and in-situ resource utilization experiments.',
    team: ['Dr. Sarah Chen', 'Marcus Rodriguez', 'Yuki Tanaka', 'Pavel Volkov'],
    subsystems: ['Propulsion', 'Avionics', 'Life Support', 'Power', 'Thermal', 'Communications', 'GNC', 'Structure'],
    telemetry: { altitude: '384,400 km', velocity: '1.022 km/s', met: 'T-327d 14h', commStatus: 'NOMINAL', powerStatus: '98.2%' },
  },
  {
    id: 'MSN-002',
    name: 'EUROPA CLIPPER',
    codename: 'Ice Piercer',
    phase: 'Critical Design',
    phaseIndex: 4,
    healthScore: 91,
    completion: 67,
    riskLevel: 'low',
    status: 'active',
    launchDate: '2027-10-01T09:00:00Z',
    color: '#00C8FF',
    description: 'Orbiter mission to conduct detailed reconnaissance of Jupiter\'s moon Europa, investigating the subsurface ocean and assessing habitability potential.',
    team: ['Dr. Amara Osei', 'James Wright', 'Li Wei', 'Elena Vasquez'],
    subsystems: ['Propulsion', 'Avionics', 'Instruments', 'Power', 'Thermal', 'Communications', 'Radiation Shielding', 'Structure'],
    telemetry: { altitude: '628,300,000 km', velocity: '24.1 km/s', met: 'T-524d 03h', commStatus: 'NOMINAL', powerStatus: '99.1%' },
  },
  {
    id: 'MSN-003',
    name: 'MARS ASCENT',
    codename: 'Red Return',
    phase: 'System Requirements',
    phaseIndex: 2,
    healthScore: 56,
    completion: 23,
    riskLevel: 'high',
    status: 'warning',
    launchDate: '2028-07-20T16:00:00Z',
    color: '#FF3B5C',
    description: 'Mars Ascent Vehicle development for sample return mission. First-ever launch from another planet surface with collected geological samples.',
    team: ['Dr. Raj Patel', 'Ingrid Larsson', 'Omar Hassan', 'Maria Costa'],
    subsystems: ['Propulsion', 'Avionics', 'Sample Container', 'Power', 'Thermal', 'Communications', 'GNC', 'Structure'],
    telemetry: { altitude: 'SURFACE', velocity: '0 km/s', met: 'T-1182d', commStatus: 'DELAYED 12m', powerStatus: '94.7%' },
  },
  {
    id: 'MSN-004',
    name: 'LUNAR GATEWAY',
    codename: 'Orbital Haven',
    phase: 'Integration & Test',
    phaseIndex: 5,
    healthScore: 85,
    completion: 78,
    riskLevel: 'low',
    status: 'active',
    launchDate: '2026-12-01T11:00:00Z',
    color: '#FFB830',
    description: 'Multi-module space station in lunar orbit serving as staging point for deep space missions and lunar surface access.',
    team: ['Col. Thomas Park', 'Dr. Fatima Al-Rashid', 'Aleksei Morozov', 'Sophie Laurent'],
    subsystems: ['Propulsion', 'Docking', 'ECLSS', 'Power', 'Thermal', 'Communications', 'GNC', 'Habitat'],
    telemetry: { altitude: '70,000 km NRHO', velocity: '0.82 km/s', met: 'T-221d 08h', commStatus: 'NOMINAL', powerStatus: '97.5%' },
  },
  {
    id: 'MSN-005',
    name: 'TITAN EXPLORER',
    codename: 'Dragonfly',
    phase: 'Concept of Operations',
    phaseIndex: 1,
    healthScore: 95,
    completion: 12,
    riskLevel: 'low',
    status: 'active',
    launchDate: '2030-04-15T08:00:00Z',
    color: '#00C8FF',
    description: 'Rotorcraft lander mission to Saturn\'s moon Titan, exploring diverse locations to investigate prebiotic chemistry and search for biosignatures.',
    team: ['Dr. Nina Kowalski', 'Hiroshi Yamamoto', 'Abigail Foster', 'Kwame Asante'],
    subsystems: ['Rotors', 'Avionics', 'Instruments', 'RTG Power', 'Thermal', 'Communications', 'GNC', 'Structure'],
    telemetry: { altitude: 'N/A', velocity: 'N/A', met: 'PLANNING', commStatus: 'STANDBY', powerStatus: 'N/A' },
  },
  {
    id: 'MSN-006',
    name: 'KEPLER STATION',
    codename: 'Starwatch',
    phase: 'Detailed Design',
    phaseIndex: 4,
    healthScore: 88,
    completion: 55,
    riskLevel: 'medium',
    status: 'active',
    launchDate: '2027-06-30T20:00:00Z',
    color: '#00FF9D',
    description: 'Next-generation space telescope with 25m segmented primary mirror for direct imaging of Earth-like exoplanets and atmospheric characterization.',
    team: ['Dr. Claire Dubois', 'Maxwell Green', 'Anika Sharma', 'Diego Morales'],
    subsystems: ['Optics', 'Avionics', 'Instruments', 'Power', 'Thermal', 'Communications', 'Pointing Control', 'Sunshield'],
    telemetry: { altitude: 'L2 Halo', velocity: '0.21 km/s', met: 'T-432d 16h', commStatus: 'NOMINAL', powerStatus: '99.8%' },
  },
];

export const requirements = {
  'MSN-001': [
    { id: 'REQ-001', text: 'The system shall sustain a crew of 4 astronauts for a minimum of 30 days on the lunar surface.', status: 'verified', level: 'system', priority: 'critical', verification: 'test', parent: 'STK-001' },
    { id: 'REQ-002', text: 'The thermal control system shall maintain cabin temperature between 18°C and 26°C.', status: 'verified', level: 'subsystem', priority: 'high', verification: 'test', parent: 'REQ-001' },
    { id: 'REQ-003', text: 'The communication system shall maintain continuous contact with Earth via Lunar Gateway relay.', status: 'draft', level: 'system', priority: 'critical', verification: 'demonstration', parent: 'STK-002' },
    { id: 'REQ-004', text: 'The power subsystem shall generate a minimum of 12 kW continuous power using solar arrays.', status: 'verified', level: 'subsystem', priority: 'high', verification: 'analysis', parent: 'REQ-001' },
    { id: 'REQ-005', text: 'The propulsion system shall provide sufficient delta-v for lunar orbit insertion and descent.', status: 'in-review', level: 'system', priority: 'critical', verification: 'analysis', parent: 'STK-003' },
    { id: 'REQ-006', text: 'The life support system shall adequately handle crew needs.', status: 'draft', level: 'subsystem', priority: 'high', verification: 'test', parent: 'REQ-001' },
    { id: 'REQ-007', text: 'The avionics shall support autonomous landing with precision of ±100m.', status: 'verified', level: 'subsystem', priority: 'critical', verification: 'test', parent: 'REQ-005' },
    { id: 'REQ-008', text: 'Radiation shielding shall limit crew exposure to less than 50 mSv per mission.', status: 'failed', level: 'subsystem', priority: 'critical', verification: 'analysis', parent: 'REQ-001' },
    { id: 'REQ-009', text: 'All software systems shall comply with NASA NPR 7150.2 software engineering requirements.', status: 'verified', level: 'system', priority: 'medium', verification: 'inspection', parent: 'STK-004' },
    { id: 'REQ-010', text: 'The ISRU system shall ideally process regolith for oxygen extraction.', status: 'draft', level: 'subsystem', priority: 'medium', verification: 'demonstration', parent: 'STK-005' },
  ],
  'MSN-003': [
    { id: 'REQ-047', text: 'The MAV shall achieve Mars orbit injection velocity of 3.55 km/s.', status: 'draft', level: 'system', priority: 'critical', verification: 'analysis', parent: 'STK-010' },
    { id: 'REQ-083', text: 'The sample container shall maintain hermetic seal during ascent.', status: 'draft', level: 'subsystem', priority: 'critical', verification: 'test', parent: 'REQ-047' },
    { id: 'REQ-091', text: 'The propulsion system shall operate in Mars ambient temperature range (-60°C to +20°C).', status: 'draft', level: 'subsystem', priority: 'critical', verification: 'test', parent: 'REQ-047' },
  ]
};

export const risks = {
  'MSN-001': [
    { id: 'RSK-001', title: 'Lunar dust contamination of EVA suit seals', likelihood: 4, consequence: 4, status: 'active', mitigation: 'Advanced electrostatic dust repulsion system under development', owner: 'Dr. Sarah Chen' },
    { id: 'RSK-002', title: 'Communication blackout during far-side operations', likelihood: 3, consequence: 3, status: 'mitigated', mitigation: 'Gateway relay constellation provides 98.5% coverage', owner: 'Yuki Tanaka' },
    { id: 'RSK-003', title: 'Solar array degradation from micrometeorite impacts', likelihood: 2, consequence: 4, status: 'active', mitigation: 'Redundant array design with 130% rated capacity', owner: 'Pavel Volkov' },
    { id: 'RSK-004', title: 'Crew radiation exposure exceeding design limits', likelihood: 3, consequence: 5, status: 'critical', mitigation: 'Redesign shelter module with enhanced water wall shielding', owner: 'Marcus Rodriguez' },
    { id: 'RSK-005', title: 'ISRU oxygen production rate below threshold', likelihood: 3, consequence: 2, status: 'monitoring', mitigation: 'Backup O2 supply sized for 120% mission duration', owner: 'Dr. Sarah Chen' },
  ],
  'MSN-003': [
    { id: 'RSK-010', title: 'Solid propellant grain cracking in Mars thermal cycling', likelihood: 4, consequence: 5, status: 'critical', mitigation: 'New propellant formulation with wider temperature tolerance', owner: 'Dr. Raj Patel' },
    { id: 'RSK-011', title: 'Sample container seal failure during ascent vibration', likelihood: 3, consequence: 5, status: 'active', mitigation: 'Triple-redundant seal design with vibration damping', owner: 'Omar Hassan' },
  ]
};

export const lifecyclePhases = [
  { id: 'phase-0', name: 'Mission Need', side: 'left', index: 0, verifiedBy: 'Stakeholder Acceptance' },
  { id: 'phase-1', name: 'Concept of Operations', side: 'left', index: 1, verifiedBy: 'Mission Validation' },
  { id: 'phase-2', name: 'System Requirements', side: 'left', index: 2, verifiedBy: 'System Verification' },
  { id: 'phase-3', name: 'Architecture Design', side: 'left', index: 3, verifiedBy: 'Subsystem Integration' },
  { id: 'phase-4', name: 'Detailed Design', side: 'left', index: 4, verifiedBy: 'Unit Test' },
  { id: 'phase-5', name: 'Integration', side: 'bottom', index: 5, verifiedBy: null },
  { id: 'phase-6', name: 'Unit Test', side: 'right', index: 4, verifiedBy: null },
  { id: 'phase-7', name: 'Subsystem Integration', side: 'right', index: 3, verifiedBy: null },
  { id: 'phase-8', name: 'System Verification', side: 'right', index: 2, verifiedBy: null },
  { id: 'phase-9', name: 'Mission Validation', side: 'right', index: 1, verifiedBy: null },
  { id: 'phase-10', name: 'Stakeholder Acceptance', side: 'right', index: 0, verifiedBy: null },
];

export const subsystemLibrary = [
  { id: 'sub-prop', name: 'Propulsion', abbr: 'PROP', color: '#FF3B5C', icon: 'rocket', category: 'Mechanical' },
  { id: 'sub-pwr', name: 'Power', abbr: 'PWR', color: '#FFB830', icon: 'power', category: 'Electrical' },
  { id: 'sub-thm', name: 'Thermal', abbr: 'THM', color: '#FF6B35', icon: 'thermal', category: 'Mechanical' },
  { id: 'sub-avn', name: 'Avionics', abbr: 'AVN', color: '#00C8FF', icon: 'avionics', category: 'Electrical' },
  { id: 'sub-com', name: 'Communications', abbr: 'COM', color: '#00FF9D', icon: 'comms', category: 'Electrical' },
  { id: 'sub-gnc', name: 'GNC', abbr: 'GNC', color: '#B388FF', icon: 'gnc', category: 'Software' },
  { id: 'sub-str', name: 'Structure', abbr: 'STR', color: '#90A4AE', icon: 'structure', category: 'Mechanical' },
  { id: 'sub-pld', name: 'Payload', abbr: 'PLD', color: '#4DD0E1', icon: 'payload', category: 'Mission' },
];

export const telemetryStreams = [
  { label: 'ALT', value: '384,400', unit: 'km', mission: 'ARTEMIS-VII', status: 'nominal' },
  { label: 'VEL', value: '1.022', unit: 'km/s', mission: 'ARTEMIS-VII', status: 'nominal' },
  { label: 'MET', value: 'T-327d 14h 22m', unit: '', mission: 'ARTEMIS-VII', status: 'nominal' },
  { label: 'COMM', value: 'LINK ACTIVE', unit: '', mission: 'ARTEMIS-VII', status: 'nominal' },
  { label: 'PWR', value: '98.2', unit: '%', mission: 'ARTEMIS-VII', status: 'nominal' },
  { label: 'ALT', value: '628.3M', unit: 'km', mission: 'EUROPA CLIPPER', status: 'nominal' },
  { label: 'VEL', value: '24.1', unit: 'km/s', mission: 'EUROPA CLIPPER', status: 'nominal' },
  { label: 'COMM', value: 'LINK ACTIVE', unit: '', mission: 'EUROPA CLIPPER', status: 'nominal' },
  { label: 'RAD', value: '12.4', unit: 'krad', mission: 'EUROPA CLIPPER', status: 'warning' },
  { label: 'FUEL', value: '73.1', unit: '%', mission: 'MARS ASCENT', status: 'nominal' },
  { label: 'TEMP', value: '-43', unit: '°C', mission: 'MARS ASCENT', status: 'nominal' },
  { label: 'COMM', value: '12m DELAY', unit: '', mission: 'MARS ASCENT', status: 'warning' },
  { label: 'PWR', value: '97.5', unit: '%', mission: 'LUNAR GATEWAY', status: 'nominal' },
  { label: 'DOCK', value: 'ALIGNED', unit: '', mission: 'LUNAR GATEWAY', status: 'nominal' },
  { label: 'O2', value: '21.3', unit: '%', mission: 'LUNAR GATEWAY', status: 'nominal' },
  { label: 'MIRROR', value: 'DEPLOYED', unit: '', mission: 'KEPLER STATION', status: 'nominal' },
  { label: 'TEMP', value: '-233', unit: '°C', mission: 'KEPLER STATION', status: 'nominal' },
];
